### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by kerrzy** [ZeekDaGeek/codevanilla-public#2]
ok so i start up the game make a world and it crashes says out of Memory when i try to join server it crashes idk whats going on im bad with mods sorry

**Comment by ZeekDaGeek** [comment]
Can I get the crash log?

**Comment by kerrzy** [comment]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 18/01/15 12:26 AM
Description: Ticking screen

java.lang.OutOfMemoryError: Ticking screen
    at sun.misc.Unsafe.allocateMemory(Native Method)
    at java.nio.DirectByteBuffer.<init>(Unknown Source)
    at java.nio.ByteBuffer.allocateDirect(Unknown Source)
    at mapwriter.MwUtil.allocateDirectIntBuffer(MwUtil.java:89)
    at mapwriter.Texture.<init>(Texture.java:20)
    at mapwriter.map.UndergroundTexture.<init>(UndergroundTexture.java:63)
    at mapwriter.Mw.load(Mw.java:510)
    at mapwriter.Mw.onChunkLoad(Mw.java:642)
    at mapwriter.forge.EventHandler.eventChunkLoad(EventHandler.java:23)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_256_EventHandler_eventChunkLoad_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.multiplayer.ChunkProviderClient.func_73158_c(ChunkProviderClient.java:59)
    at net.minecraft.client.multiplayer.WorldClient.func_73025_a(WorldClient.java:144)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147269_a(NetHandlerPlayClient.java:1185)
    at net.minecraft.network.play.server.S26PacketMapChunkBulk.func_148833_a(S26PacketMapChunkBulk.java:184)
    at net.minecraft.network.play.server.S26PacketMapChunkBulk.func_148833_a(S26PacketMapChunkBulk.java:242)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at sun.misc.Unsafe.allocateMemory(Native Method)
    at java.nio.DirectByteBuffer.<init>(Unknown Source)
    at java.nio.ByteBuffer.allocateDirect(Unknown Source)
    at mapwriter.MwUtil.allocateDirectIntBuffer(MwUtil.java:89)
    at mapwriter.Texture.<init>(Texture.java:20)
    at mapwriter.map.UndergroundTexture.<init>(UndergroundTexture.java:63)
    at mapwriter.Mw.load(Mw.java:510)
    at mapwriter.Mw.onChunkLoad(Mw.java:642)
    at mapwriter.forge.EventHandler.eventChunkLoad(EventHandler.java:23)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_256_EventHandler_eventChunkLoad_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.multiplayer.ChunkProviderClient.func_73158_c(ChunkProviderClient.java:59)
    at net.minecraft.client.multiplayer.WorldClient.func_73025_a(WorldClient.java:144)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147269_a(NetHandlerPlayClient.java:1185)
    at net.minecraft.network.play.server.S26PacketMapChunkBulk.func_148833_a(S26PacketMapChunkBulk.java:184)
    at net.minecraft.network.play.server.S26PacketMapChunkBulk.func_148833_a(S26PacketMapChunkBulk.java:242)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
    Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Kerrzy'/529012, l='MpServer', x=212.50, y=67.62, z=244.50]]
    Chunk stats: MultiplayerChunkCache: 1, 1
    Level seed: 0
    Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (204,64,252), Chunk: (at 12,4,12 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 10524952 game time, 11126062 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 4 total; [EntityItemFrame['Item Frame'/529144, l='MpServer', x=91.50, y=70.50, z=114.94], EntityItemFrame['Item Frame'/529145, l='MpServer', x=90.50, y=70.50, z=114.94], EntityClientPlayerMP['Kerrzy'/529012, l='MpServer', x=212.50, y=67.62, z=244.50], EntityItemFrame['Item Frame'/529143, l='MpServer', x=89.50, y=70.50, z=114.94]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (x86) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 328319888 bytes (313 MB) / 510066688 bytes (486 MB) up to 1020067840 bytes (972 MB)
    JVM Flags: 17 total; -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1284 Minecraft Forge 10.13.2.1284 35 mods loaded, 35 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1284} [Forge Mod Loader](forge-1.7.10-10.13.2.1284-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1284} [Minecraft Forge](forge-1.7.10-10.13.2.1284-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.4.35} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.4.83} [Not Enough Items](notenoughitems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PlayerAPI{1.1} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]armorstatushud-client-1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]statuseffecthud-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppleCore{1.0.2} [AppleCore](applecore-mc1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core](cofhcore-[1.7.10]3.0.0b9-95.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    asielib{0.3.8} [asielib](asielib-1.7.10-0.3.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ComputerCraft{1.65} [ComputerCraft](computercraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenComputers{1.4.5.28} [OpenComputers](opencomputers-mc1.7.10-1.4.5.28-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    computronics{1.3.4} [Computronics](computronics-1.7.10-1.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    eirairc{mc1.7.10-v2.8.42} [EiraIRC](eirairc-mc1.7.10-v2.8.45.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraUtilities{1.2.1} [Extra Utilities](extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FlatSigns{2.1.0.19} [Flat Signs](flatsigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ganyssurface{1.9.4} [Gany's Surface](ganys-surface-1.9.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](inventorytweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MapWriter{2.1710.1} [MapWriter](mapwriter-1.7.10-2.1710.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OCS{1.7.3} [OpenCCSensors](openccsensors-1.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    openglasses{1.0.43} [OC Glasses](openglasses-1.0.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenMods{0.6} [OpenMods](openmodslib-1.7.10-0.6-snapshot-291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenPeripheralCore{0.5.0} [OpenPeripheralCore](openperipheralcore-1.7.10-0.5.0-snapshot-185.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenPeripheral{0.2.0} [OpenPeripheralAddons](openperipheraladdons-1.7.10-0.2.0-snapshot-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenPeripheralIntegration{0.1.0} [OpenPeripheralIntegration](openperipheralintegration-1.7.10-0.1.0-snapshot-27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RandomThings{2.2.3} [Random Things](randomthings-2.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Squeedometer{1.0.3} [Squeedometer](squeedometer-mc1.7.x-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Squake{1.0.1} [Squake](squake-mc1.7.x-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    denseores{1.0} [Dense Ores](denseores-1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.3.12804 Compatibility Profile Context 13.352.1004.1007, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

is that the right one?

**Comment by ZeekDaGeek** [comment]
Yep, that seems to be the right one.

Follow these steps for me:
- In the bottom left click on the Windows button.
- Right click on "Computer" and go down to "Properties".
- Under the "System" category:
  - What does your "Installed Memory" say?
  - What does your "System Type" say?

**Comment by ZeekDaGeek** [comment]
Actually ignore all of that, it's in your crash log apparently. You have 1GB of Memory on a 32 bit operating system.

Are you trying to use MultiMC or the FTB Launcher?

**Comment by kerrzy** [comment]
mmc

**Comment by ZeekDaGeek** [comment]
In MultiMC:
- Right click on Code Vanilla and go down to "Edit Instance".
- On the left hand side of the box that pops up click on "Settings"
- Change the "Minimum memory allocation" value to 512 MB
- Change the "Maximum memory allocation" value to 768 MB

Try creating your world after that.

**Comment by kerrzy** [comment]
crashed again did u still want those specs or what ever they wear ?

**Comment by ZeekDaGeek** [comment]
Sure.

**Comment by kerrzy** [comment]
8.00gb (6.96gb usable) 

64-bit operating system, x64-based processor

**Comment by ZeekDaGeek** [comment]
Hmm then it looks like you have the incorrect version of Java installed. If you have a 32 bit version of Java it makes Minecraft think it can only use 1GB of ram or less.

Make sure you download the 64bit version from here:
https://java.com/en/download/manual.jsp

Once you've install it make sure that MultiMC is using the proper version of Java to run Minecraft. To do that along the top click on "Settings" and then click the "Java" category. If you select Auto Detect you will be presented with a series of options. You want the 1.8.0_\* version of javaw.exe with the 64 "Arch"

**Comment by kerrzy** [comment]
it works <3

**Comment by ZeekDaGeek** [comment]
Enjoy!
